hydra:
  job:
    name: loss_llrd_grid_1
  sweeper:
    params:
      loss.use_coral_objective: false,true
      loss.use_weighted_loss: false,true
      loss.aux_multilabel_plc_loss_weight: 0.0,0.1,0.25,0.5
      loss.use_weighted_aux_loss: false,true

optim:
  optim: adamw
  lr: 1e-5
  wd: 0.05
  lldr:
    enabled: true
    lr_head: 1e-5
    lr_top: 1e-5
    layer_decay: 0.95

loss:
  focal_loss_lambda: 0.0

wandb:
  tags: [loss_llrd_grid_1]